# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'

target 'Mac-Tour' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mac-Tour
  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'SwiftyJSON', '~> 4.0'
end
